### ISSUE TITLE
Can't run/ start the insturment.

### ISSUE THREAD

**Issue by profesionalleet1337** [U7P4L-IN/SMS-BOMBER#2]
Hello, when I tried to start , and type the command you shared : python3 SMS-BOMBER.py , I got this message :
python3: can't open file '/home/myname/SMS-BOMBER/SMS-BOMBER.py': [Errno 2] No such file or directory
Where is the problem, I entered all command, you shared and still can't run the tool ?

**Comment by U7P4L-IN** [comment]
bro i'm sry.cz i chg the file name. you will type on termux "ls" and see new one file .its name  'sms.py; .run this file

**Comment by profesionalleet1337** [comment]
> bro i'm sry.cz i chg the file name. you will type on termux "ls" and see new one file .its name 'sms.py; .run this file

I'm unsing on google cloud shell/ or linux. Could u guide me, what to do ?

**Comment by U7P4L-IN** [comment]
maybe you will face error on this time
